FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
# Доустанавливаем специфичные для API библиотеки, если их нет в requirements
RUN pip install fastapi uvicorn python-multipart

# Копируем код
COPY . .

# Запускаем сервер на порту 8000
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]